package common;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;
import module.auth.AuthModel;
import module.config.ConfigModel;
import module.data.DataModel;
import module.log.LogModel;
import module.table.DataTableModel;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

    public static void mapping(ActiveRecordPlugin arp) {
        arp.addMapping("data", DataModel.class);
        arp.addMapping("auth", AuthModel.class);
        arp.addMapping("config", ConfigModel.class);
        arp.addMapping("log", LogModel.class);
        arp.addMapping("dataTable", DataTableModel.class);
    }
}

